# Generated by Django 5.0.1 on 2024-01-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_role_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('folio', models.CharField(max_length=150)),
                ('fecha_de_atencion', models.DateTimeField()),
                ('cliente', models.CharField(max_length=150)),
                ('sitio', models.CharField(max_length=150)),
                ('site_id_telmex', models.IntegerField()),
                ('ciudad', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
                ('proveedor_IDC', models.CharField(max_length=150)),
                ('coordinador_IDC', models.CharField(max_length=150)),
                ('hora_llegada_a_sitio', models.TimeField()),
                ('hora_de_ingreso_a_sucursal', models.TimeField()),
                ('hora_frente_equipo', models.TimeField()),
                ('hora_de_salida', models.TimeField()),
                ('tiempo_en_sitio', models.TimeField()),
                ('status', models.CharField(max_length=150)),
                ('costo_servicio', models.FloatField()),
                ('costo_recoleccion', models.FloatField()),
                ('retiro', models.FloatField(blank=True)),
                ('viaticos', models.FloatField(blank=True)),
                ('costo_herramienta', models.FloatField(blank=True)),
                ('total', models.FloatField()),
                ('servicio_pagado', models.FloatField(blank=True)),
                ('viatico_pagado', models.FloatField(blank=True)),
                ('recoleccion_pagada', models.FloatField(blank=True)),
                ('herramienta', models.FloatField(blank=True)),
                ('total_pagado', models.FloatField(blank=True)),
                ('penalizacion', models.FloatField(blank=True)),
                ('observaciones', models.CharField(max_length=150)),
                ('cuenta_por_pagar', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
