# Generated by Django 5.0.1 on 2024-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_basegeneral_intervalotiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalotiempo',
            name='hora_fin',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='intervalotiempo',
            name='hora_inicio',
            field=models.DurationField(),
        ),
    ]
