# Generated by Django 5.0.1 on 2024-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_intervalotiempo_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalotiempo',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='intervalotiempo',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
